// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
    export interface GlobalComponents {
        ElButton: typeof import('element-plus/es')['ElButton']
        ElCard: typeof import('element-plus/es')['ElCard']
        ElDivider: typeof import('element-plus/es')['ElDivider']
        ElForm: typeof import('element-plus/es')['ElForm']
        ElFormItem: typeof import('element-plus/es')['ElFormItem']
        ElInput: typeof import('element-plus/es')['ElInput']
        Navigation: typeof import('./src/components/layout/Navigation.vue')['default']
    }
}

export {}
